### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by Koutro44** [DamagingRose/Rose-Grabber#118]
after i completed all of the installation process and finished with the bat file, after I run the created .exe file I get these errors:

Traceback (most recent call last):
  File "main.py", line 2, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "rose_rat.py", line 7, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "cv2\__init__.py", line 181, in <module>
  File "cv2\__init__.py", line 153, in bootstrap
  File "importlib\__init__.py", line 126, in import_module
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "cv2\__init__.py", line 181, in <module>
  File "cv2\__init__.py", line 76, in bootstrap
ImportError: ERROR: recursion is detected during loading of "cv2" binary extensions. Check OpenCV installation.

**Comment by gumbobr0t** [comment]
disable windows defender for building, also download the latest python version and make sure to update all libs by uninstalling & then letting the bat file install them again

`python -m pip uninstall -r requirements.txt`

**Comment by Koutro44** [comment]
> disable windows defender for building, also download the latest python version and make sure to update all libs by uninstalling & then letting the bat file install them again
> 
> `python -m pip uninstall -r requirements.txt`


I did that and now I get a different error:

Traceback (most recent call last):
  File "main.py", line 2, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "rose_rat.py", line 2, in <module>
ModuleNotFoundError: No module named '__webhook'

**Comment by gumbobr0t** [comment]
looks like you still did not disable windows defender & re-downloaded the project

**Comment by Koutro44** [comment]
so I am supposed to delete all of it and redownload it without defender?

**Comment by gumbobr0t** [comment]
yep, disable defender, delete the folders because defender probably already deleted contents of it

**Comment by gumbobr0t** [comment]
& then download again, extract the zip & run the start.bat

**Comment by Koutro44** [comment]
thank you very much, it worked! Although, this as well as my info showed up in the webhook messages. Should I be concerned?

Command 'wmic csproduct get uuid' returned non-zero exit status 2147749898.

**Comment by gumbobr0t** [comment]
"First notice that [WMIC is deprecated](https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/hh831568(v=ws.11)#wmi-providers). You will eventually want to switch to PS cmdlets.

The next step to debug this would be to see what, if anything, is available from wmic csproduct by calling wmic csproduct get without specifying UUID as the key to get.

You will likely find that the UUID is not available to WMI. This is very likely because the customer of yours with the OS you don't control is using a hacked/modified/unlicensed copy of windows or a modified SMBIOS. There could be other explanations, but that's the most likely. Correcting that isn't really something within your power.

If you want to investigate further you could use PS:

`Get-WmiObject -Class Win32_ComputerSystemProduct | Select-Object -Property UUID`
However, you will find the UUID isn't there (otherwise wmic would have returned it)."

## Thanks for the feedback!

**Probably has something to do with your specific windows version. However, I will keep searching for a fix.**

Have a nice day & enjoy 🌹! :)
