### ISSUE TITLE
Error opening the code

### ISSUE THREAD

**Issue by RandomPolishMan** [DamagingRose/Rose-Grabber#138]
Good afternoon.

I followed the instructions on the 'SETUP' sub-topic from 'README.dm'. When I tried running start.bat, my cmd just popped up for half a second before disappearing again. 

For that reason, I'd like to know ALL the requirements that need to be fulfilled in order to run the code. And this includes the smallest of things, such as having an admin account on Windows, having Python installed with admin rights, etc.

Thanks for your time.

**Comment by gumbobr0t** [comment]
and you ran install.bat before? also, may you execute the following commands in a command prompt inside of the rose-grabber directory?
`$ pip install -U -r components/scrapedata/requirements.txt`
`$ start.bat`

**Comment by gumbobr0t** [comment]
and show me the output of the second command then, thanks

sorry for the late answer btw

**Comment by RandomPolishMan** [comment]
Good afternoon,

Apologies for wasting your time, I have now just realized I hadn't Python installed on this computer.

For my own safety reasons:
1) Is it possible to run the code without needing to give Python Admin rights?
2) As the answer to the previous question is already expected, I'd like to know how I can check your code's safety before giving it Admin rights.

I'm asking these questions because Windows' anti-virus was going crazy both during the download of the zip file and the execution of the 'install.bat' file.

You do not need to apologize for the late reply.

Thanks again for your time.

**Comment by gumbobr0t** [comment]
> Good afternoon,
> 
> Apologies for wasting your time, I have now just realized I hadn't Python installed on this computer.
> 
> For my own safety reasons:
> 1) Is it possible to run the code without needing to give Python Admin rights?
> 2) As the answer to the previous question is already expected, I'd like to know how I can check your code's safety before giving it Admin rights.
> 
> I'm asking these questions because Windows' anti-virus was going crazy both during the download of the zip file and the execution of the 'install.bat' file.
> 
> You do not need to apologize for the late reply.
> 
> Thanks again for your time.

Hey, I like that at least one person on the internet actually do cares about their privacy and safety.

As of my knowledge, you don't need to give the script admin rights, only the python installer needs them to install the software. Rose is not associated with the python installer.

Your windows defender went crazy during thw download, because our tool sues an algorithm to convert the actual source code files into an executable. But for that we need the source files, which are detected by microsoft defender. So a quick overview:
```
Press build -> editing the actual malwares code and set your specific config -> convert the source code files into an exe
```

For the installation batch script it may be detected as a dropper or binder, because it checks for your python and tries to scrape the official python installer and quietly install python, that us detected as a malware algortihm, because many tools or malware at all uses this to download other malicious code.

To check if our project contains any malicious code, I'd recommend you joining our telegram group channel and ask the participants for their opinion! Or you could give an expert the program and let them check it. Our tool is fully open source, so you could even look inside of the components directory for all the contents freely, but that would require at least a bit understanding of python.

I hope I could answer all your questions.
Feel free to dm me on [discord](https://discordlookup.com/user/1150068078663704616) when you are experiencing any other trouble. ❤️
